/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeffplaisance_jeffdiff_JeffZip */

#ifndef _Included_com_jeffplaisance_jeffdiff_JeffZip
#define _Included_com_jeffplaisance_jeffdiff_JeffZip
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jeffplaisance_jeffdiff_JeffZip_blockSize
#define com_jeffplaisance_jeffdiff_JeffZip_blockSize 6L
#undef com_jeffplaisance_jeffdiff_JeffZip_HASH_SIZE
#define com_jeffplaisance_jeffdiff_JeffZip_HASH_SIZE 32768L
#undef com_jeffplaisance_jeffdiff_JeffZip_HASH_MASK
#define com_jeffplaisance_jeffdiff_JeffZip_HASH_MASK 32767L
/*
 * Class:     com_jeffplaisance_jeffdiff_JeffZip
 * Method:    compress
 * Signature: (Ljava/nio/ByteBuffer;JILjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_com_jeffplaisance_jeffdiff_JeffZip_compress
  (JNIEnv *, jclass, jobject, jlong, jint, jobject, jlong);

/*
 * Class:     com_jeffplaisance_jeffdiff_JeffZip
 * Method:    decompress
 * Signature: (Ljava/nio/ByteBuffer;JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_com_jeffplaisance_jeffdiff_JeffZip_decompress
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
